# Generated by Django 3.0.5 on 2020-06-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('con_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlasmaDonor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('created_date', models.DateTimeField()),
            ],
        ),
    ]
